### ISSUE TITLE
How do I re render the page like your example

### ISSUE THREAD

**Issue by s89146892002** [duongxuannam/react-native-check-notification-permission#1]
Hi! I am a rookie in react native
How can I re render the page while I finish changed the notification setting in android ?
I set the button call the function like following
`  async test() {
    changeNotificationSetting();
    await checkNotificationPermission().then((result) => {
      console.log("ReturnMsg:   " + result)
      this.setState({
        Noti: result,
      });
    });
    console.log(this.state.Noti)
  }`

The checkNotificationPermission faster than the changeNotificationSetting that I could not setState the Noti that I changed.

If you have any suggestions please help me. Thank you!

**Comment by duongxuannam** [comment]
sorry for the late reply. You can use [AppState](https://facebook.github.io/react-native/docs/appstate) to check permisson when returning to the app from the setting screen like this:
```
import {AppState} from 'react-native';
import {checkNotificationPermission} from 'react-native-check-notification-permission';

componentDidMount() {
    AppState.addEventListener('change', this._handleAppStateChange);
  }

 _handleAppStateChange = (nextAppState) => {
    try {
      if (
        this.state.appState.match(/inactive|background/) &&
        nextAppState === 'active'
      ) {
	const bool = await checkNotificationPermission();
           .....
      }
      this.setState({ appState: nextAppState });
    }
    catch{ 
    }
  }

```
