### ISSUE TITLE
Undefined symbol.

### ISSUE THREAD

**Issue by motogod** [duongxuannam/react-native-check-notification-permission#2]
Hi,

Thanks for the library that is what I want.

But I get some problem when I try to install it on XCode.

My React Native version is:
`"react-native": "0.57.1"`

Here is my step about installing the library:
1.
`yarn add react-native-check-notification-permission`
2.
`react-native link react-native-check-notification-permission`
3.
`I had checked libRNCheckNotificationPermission.a to my project's Build Phases.`
4.
`I had set Always Embed Swift Standard Libraries to Yes`

But I'm not very sure about 
`Because library written in Swift you need to add this $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) to the library search paths of your target. `

So I add it in Framework Search Paths
<img width="857" alt="螢幕快照 2019-10-24 下午5 02 36" src="https://user-images.githubusercontent.com/17781603/67470685-bede5780-f680-11e9-9a4c-e929d4f7f18a.png">

Clean and build get a lot of swift errors

`Undefined symbol: Foundation._convertErrorToNSError(Swift.Error) -> __C.NSError`

<img width="1121" alt="螢幕快照 2019-10-24 下午5 05 17" src="https://user-images.githubusercontent.com/17781603/67470736-d74e7200-f680-11e9-87dc-a35b1822fb88.png">

Can I get some suggestions ?  Thanks a lot.

**Comment by duongxuannam** [comment]
Sorry for late reply. you just add `$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)` to the library search paths of your target and set `You also set Always Embed Swift Standard Libraries` to `Yes` like documents

**Comment by motogod** [comment]
Sorry I don't get your point. So I add `$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)` into my Framework Search Paths is correct ?

Thanks for your reply.

**Comment by duongxuannam** [comment]
yeah. It will help the project object c of react-native understand code write by Swift code. maybe :D i just javascipt developer do not understand very deeply ios. goodluck

**Comment by motogod** [comment]
Thanks. I will try it again.
