### ISSUE TITLE
Add homeage parameter to the pod file

### ISSUE THREAD

**Issue by DanielDanaee** [duongxuannam/react-native-check-notification-permission#4]
at:

`ios/RNCheckNotificationPermission.podspec`
```
[!] The `RNCheckNotificationPermission` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.
```

**Comment by DanielDanaee** [comment]
Please provide an update on this.

**Comment by Pascip** [comment]
I fixed this error by adding something into the RNCheckNotificationPermission.podspec file. Just add anything into the s.homepage parameter (I just added the URL to this repository ). Would be nice if this could be fixed in a feature release.

**Comment by duongxuannam** [comment]
Thanks @Pascip
