### ISSUE TITLE
ios Main Thread Checker: UI API called on a background thread

### ISSUE THREAD

**Issue by marlti7** [duongxuannam/react-native-check-notification-permission#5]
rn 0.59
ios

bug:Main Thread Checker: UI API called on a background thread: -[UIApplication currentUserNotificationSettings]

**Comment by duongxuannam** [comment]
hi @marlti7 . Sorry for the late reply I just got back to the origin github account. This library just updated latest react native version and support both old end new architecture. Please review if you are still interested
