### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by ghost** [duongxuannam/react-native-check-notification-permission#7]
Hello,

When trying to build the android version of the app, you will get this error:

node_modules\react-native-check-notification-permission\android\src\main\java\com\reactlibrary\RNCheckNotificationPermissionModule.java:6: error: cannot find symbol
import android.support.v4.app.NotificationManagerCompat;
                             ^
  symbol:   class NotificationManagerCompat
  location: package android.support.v4.app

I think the used API is no longer available in recent Android SDK versions, my current configuration:
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29

Thanks!

**Comment by ilialezhnev** [comment]
Hi! Same issue.

**Comment by ilialezhnev** [comment]
@ghost - [This PR](https://github.com/duongxuannam/react-native-check-notification-permission/pull/9) solves this problem

**Comment by duongxuannam** [comment]
hi @ilyalezhnev and @ghost . Sorry for the late reply I just got back to the origin github account. This library just updated latest react native version and support both old end new architecture. Please review if you are still interested
